DAO
ochenmudro/quizia pull request #12
Opened 2021-11-27 15:34 UTC by ochenmudro

2021-11-27 15:36 UTC, ochenmudro commented
Я еще интерфейсы никогда не писала, так что не уверена, насколько логично я их создала

2021-11-29 07:05 UTC, anastasiski requested changes
Я пока не буду смотреть дальше, посмотри что я написала по первому и постарайся спроецировать это на все остальные:)
Внимательно разберись с параметрами и типом возвращаемых значений, если метод get - он должен что-то возвращать, если add, то мы должны передать в него что-то, что мы будем добавлять
И посмотри по связям как последний коммент, где тебе нужно вытягивать только те сущности, которые имеют связи с какой-то другой сущностью

2021-11-29 07:05 UTC, anastasiski commented on src/main/java/com/quizia/interfaces/Answer.java
> +    void points(); // В зависимости от true или false будет начислять или не начислять балл
Тут тоже не совсем понимаю что именно наш этот метод будет делать, баллы ведь сами у нас хранятся в другой сущности
В нашем dao-слое в принципе особо нет никакой логики. Тут мы только записываем данные в бд или читаем из нее
Все какие-то расчеты и подсчеты будут происходить в слое сервисов.

2021-11-29 07:05 UTC, anastasiski commented on src/main/java/com/quizia/interfaces/Answer.java
> +}
А вот чего нам тут не хватает, так это метода для получения всех ответов по вопросу. Вот смотри. формируешь ты страничку с вопросом и нужно отобразить все ответы на этот вопрос. То есть тебе из бд по id вопроса надо вытянуть все его ответы.
Это будет что-то типа 
List<Answer> getAllByQuestionId(int questionId)

2021-11-29 08:58 UTC, anastasiski commented
Еще небольшой совет по поводу комментариев
В общем и целом оставлять комментарии к методам плохая пркатика - твой код должен быть самодокументипруемым. Чтобы когда кто-то читал название метода он понимал, что этот метод делает. В этом случае комментарии становятся излишними и бессмысленными. Если ты читаешь метод, и тебе кажется, что к нему нужно оставить комментарий, потому что не совсем понятно, что именно он делает, стоит подумать над тем, насколько правильно он назван, или может быть его логику нужно разбить на несколько более простых и понятных методов.
В качестве исключения может выступать какая-то действительно сложная бизнес-логика. с которой ты работаешь вынужденно, легаси, напоример, где ты уже не можешь ничего исправить, но хочешь как-то пояснить людям, которые потом в твой код будут смотреть, что и почему тут происходит. Второе исключение - Java Docs. Писать java-доки достаточно хорошая, но зачастую очень нелюбимая практика, потому что чтобы это было хорошо, это нужно делать правильно.
Если ты идешь по пути писания доков, то каждый public метод должен иметь javadoc, в котором описано не только то, что делает метод, но и также его входные параметры, возвращаемые значения и исключения, которые этот метод может бросить. 
Если захочешь, я тебе скину какую-нибудь ссылочку для примера:)

2021-11-29 09:16 UTC, anastasiski commented
И наверное еще общий такой более поясняющий комментарий по всему PR-y. Смотри. твой dao-слой, это только звпись данных из бд в классы и обратно. Он не делает больше никакой логики, ничего такого, он отвечает только за это. 
Вероятнее всего, тебе понадобится для каждой сущности как минимум стандартный набор CRUD-опреаций (create, read, update, delete). Их не обязательно именно так называть, но суть примерно такая. И тут уже ты должна смотреть, что именно команда делает. Например, если у нас create, это значит, мы какие-то новые данные в бд запишем. Где у нас хранятся в java rкоде наши данные? В каком-то классе, значит в такой метод мы должны передать объект нашего класса. Если у нас update, мы хотим обновить какой-то уже существующий объект, откуда мы возьмем наши значения? Они также хранятся у нас в некотором классе, значит мы туда должны положить наш новый объект и все поля из него перезаписать в нашу старую запись. Если delete, мы должны по какому-то принципу понять, какой именно объект нам надо удалить, значит есть смысл в этот метод передать id и т.д.
А остальные методы уже больше завсят от какой-то логики того, какие нам понядобятся объекты по определенному признаку, как, например, все ответы на определенный вопрос (т.е. срисок ответов по id вопроса), или все вопросы теста (т.е. список вопросов по id теста)

2021-11-30 07:00 UTC, closed without merging