POJO объекты
ochenmudro/quizia pull request #5
Opened 2021-11-12 08:08 UTC by ochenmudro

2021-11-12 09:55 UTC, anastasiski requested changes
Комментарии по поводу айдишников и объектов не стала дублировать, просто поменяй везде.
В целом, все хорошо:)
Только твои объекты должны лежать в пакете domain или model, в папочке DAO будет находиться непосредственно взаимодействие твоих лбъектов и БД
Подправь это, потом я посмотрю повнимательнее

2021-11-12 09:55 UTC, anastasiski commented on src/main/java/com/quizia/dao/Answer.java
> +    private int idanswer;
Твой id лежит уже в сущности Answer а обращаться к нему ты всегда будешь через объект, поэтому просто id будет вполне достаточно:)

2021-11-12 09:55 UTC, anastasiski commented on src/main/java/com/quizia/dao/Answer.java
> +    private int idquestion;
Смотри, мы же уже на уровне Java, нам не обязательно хранить айдишник а потом по нему еще как-то искать объект, мы можем положить в нашу сущность сам объект Queston,чтобы точно знать к какому вопросу принадлежит этот ответ

2021-11-12 09:55 UTC, anastasiski commented on src/main/java/com/quizia/dao/History.java
> +    private int idquizze;
Аналогично комментарию выше

2021-11-12 11:31 UTC, ochenmudro commented on src/main/java/com/quizia/dao/Answer.java
> +    private int idquestion;
Это получается надо ссылку на объект Question поместить в поле? Я не допёрла, что надо сделать(
@anastasiski

2021-11-15 12:21 UTC, anastasiski commented on src/main/java/com/quizia/dao/Answer.java
> +    private int idquestion;
Да, у тебя будет поле 
`private Queston question`, если связь один к одному
А если связь многие ко многим то ты можешь положить туда список
`List<Question> questions`

2021-11-16 06:57 UTC, anastasiski requested changes

2021-11-16 06:57 UTC, anastasiski commented on src/main/java/com/quizia/domain/History.java
> +    private Quizze idquizze;
Лежит объект, а имя поля id;)

2021-11-16 06:57 UTC, anastasiski commented on src/main/java/com/quizia/domain/Quizze.java
Тебе будет удобнее рабоать. если твоя связь будет двусторонняя. То есть у тебя в Тесте будет лежать список всех вопросов этого теста 
`List<Question> question`
А в вопросе ссылка на сам тест
`Quizze quizze`
Это касается всех сваязей втоих сущностей

2021-11-16 06:57 UTC, anastasiski commented on src/main/java/com/quizia/domain/Question.java
> +    private Quizze idquizze;
Аналогично исправить имя поля

2021-11-16 06:57 UTC, anastasiski commented on src/main/java/com/quizia/domain/Answer.java
> +    }
checkstyle

2021-11-16 07:02 UTC, anastasiski commented
Также мне не очень нравится твое сообщение комита
Обычно, оно не используется для взаимодействия между разработчиками, там должно быть описано **для чего** были выполненены те или иные изменения.

2021-11-16 07:27 UTC, anastasiski commented on src/main/java/com/quizia/domain/Answer.java
> +    private Question question;
Не хватает геттера/сеттера для этого поля

2021-11-18 12:54 UTC, anastasiski requested changes
Ну все, похоже, что это последние мелочи и готово!
Молодец!

2021-11-18 12:54 UTC, anastasiski commented on src/main/java/com/quizia/domain/Question.java
> +    private List<Answer> answer;
обычно если коллекция, то поле именуем во множественном числе:)

2021-11-18 12:54 UTC, anastasiski commented on src/main/java/com/quizia/domain/Quizze.java
> +    private List<Question> question;
Аналогично, question**s**

2021-11-19 08:14 UTC, anastasiski approved these changes

2021-11-19 08:15 UTC, anastasiski commented
Так как ветка для конфига отрезана от этой, пока не буду мержить, смержу все вместе поле закрытия PR по конфигу

2021-11-29 16:37 UTC, merged